language: c

sudo: required

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    # - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - sudo apt-get update && sudo apt-get install wget -y
  - .travis/install_es.sh
  - source .travis/setenv_lua.sh
  - luarocks install lunitx
  - luarocks install luacov
  - luarocks install luacov-coveralls

install:
  - luarocks make rockspecs/elasticsearch-lua-1.0.2-1.rockspec

before_script:
  - echo 'elasticsearch version ' && curl http://localhost:9200/

script:
  - cd tests
  - ./dataset/download-dataset.sh
  - lua run-tests.lua

after_success:  
  - cd ../
  - tests/run-stress-test.sh

notifications:
  email:
    on_success: change
    on_failure: always
